-- ============================================================================
-- MODULE: City Master
-- TABLE:  public.core_cities
-- DESCRIPTION: Master table for all operational and non-operational cities in LetzRyd.
-- ============================================================================

-- 1. Create Master Table
CREATE TABLE IF NOT EXISTS public.core_cities (
    city_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_code VARCHAR(10) NOT NULL UNIQUE,
    city_name VARCHAR(100) NOT NULL UNIQUE,
    state VARCHAR(100) NOT NULL,
    country VARCHAR(100) NOT NULL DEFAULT 'India',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by INTEGER NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by INTEGER NULL
);

-- Comments on table and columns for database self-documentation
COMMENT ON TABLE public.core_cities IS 'Master table storing all LetzRyd operational and inactive cities.';
COMMENT ON COLUMN public.core_cities.city_id IS 'Primary Key, auto-incrementing integer identifier.';
COMMENT ON COLUMN public.core_cities.city_code IS 'Unique alphanumeric uppercase city code (e.g. BLR, HYD, MUM).';
COMMENT ON COLUMN public.core_cities.city_name IS 'Unique official name of the city (e.g. Bangalore, Hyderabad).';
COMMENT ON COLUMN public.core_cities.state IS 'State or province where the city is located.';
COMMENT ON COLUMN public.core_cities.country IS 'Country name, defaults to India.';
COMMENT ON COLUMN public.core_cities.is_active IS 'Soft-delete flag: TRUE for active operational cities, FALSE for deactivated cities.';
COMMENT ON COLUMN public.core_cities.created_at IS 'Timestamp when the city was first registered.';
COMMENT ON COLUMN public.core_cities.created_by IS 'Identifier of the portal user who registered the city (FK to core_portal_users in future).';
COMMENT ON COLUMN public.core_cities.updated_at IS 'Timestamp of the latest modification to this city record.';
COMMENT ON COLUMN public.core_cities.updated_by IS 'Identifier of the portal user who last updated this record (FK to core_portal_users in future).';

-- 2. Automatic updated_at Function & Trigger
CREATE OR REPLACE FUNCTION public.core_set_city_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_core_cities_set_updated_at ON public.core_cities;
CREATE TRIGGER trg_core_cities_set_updated_at
BEFORE UPDATE ON public.core_cities
FOR EACH ROW
EXECUTE FUNCTION public.core_set_city_updated_at();

-- 3. Prevent Physical Deletion Function & Trigger
CREATE OR REPLACE FUNCTION public.core_prevent_city_delete()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'Physical deletion of cities is strictly prohibited. Use soft-delete (UPDATE core_cities SET is_active = FALSE) instead.';
END;
$$;

DROP TRIGGER IF EXISTS trg_core_cities_prevent_delete ON public.core_cities;
CREATE TRIGGER trg_core_cities_prevent_delete
BEFORE DELETE ON public.core_cities
FOR EACH ROW
EXECUTE FUNCTION public.core_prevent_city_delete();
