-- ==============================================================================
-- LETZRYD VEHICLE DROPOFF FINAL TABLE - PRODUCTION POSTGRESQL DDL & TRIGGERS
-- ==============================================================================
-- Master Table   : public.core_dropoffs (Single Source of Truth)
-- Filtered View  : public.active_core_dropoffs (WHERE is_deleted = FALSE)
-- Source 1       : public.sheet_dropoffs (Google Sheets Drop off History - 6,492 rows)
-- Source 2       : public.july_vehicle_dropoffs (LetzRyd Web Portal Dropoff Form - 121 rows)
-- Live Row Count : 6,531 Total (6,397 Active, 134 Soft-Deleted, 0 Sequence Gaps)
-- Host           : YOUR_DB_HOST_HERE:5432
-- Database       : postgres
-- Concurrency    : Transactional Advisory Lock 777444555
-- ID Standard    : Plain Numerical IDs (e.g. '1578') without string prefixes
-- ==============================================================================

-- ------------------------------------------------------------------------------
-- 1. UPSTREAM STAGING TABLE DEFINITIONS (IDEMPOTENT IF NOT EXISTS)
-- ------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.sheet_dropoffs (
    dropoff_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_row INTEGER UNIQUE,
    return_date DATE NOT NULL,
    return_type VARCHAR(50) NOT NULL,
    driver_id VARCHAR(50),
    driver_name VARCHAR(255),
    driver_type VARCHAR(30) DEFAULT 'Individual',
    vehicle_number VARCHAR(20) NOT NULL,
    city VARCHAR(50) NOT NULL,
    negative_balance NUMERIC(12,2) DEFAULT 0.00,
    sync_status VARCHAR(20) DEFAULT 'SYNCED',
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata'),
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata')
);

CREATE INDEX IF NOT EXISTS idx_sheet_dropoffs_vehicle ON public.sheet_dropoffs (vehicle_number);
CREATE INDEX IF NOT EXISTS idx_sheet_dropoffs_return_date ON public.sheet_dropoffs (return_date);
CREATE INDEX IF NOT EXISTS idx_sheet_dropoffs_source_row ON public.sheet_dropoffs (source_row);

CREATE TABLE IF NOT EXISTS public.july_vehicle_dropoffs (
    id SERIAL PRIMARY KEY,
    vehicle_number VARCHAR(20) NOT NULL,
    city_name VARCHAR(50),
    driver_id VARCHAR(50),
    driver_name VARCHAR(255),
    driver_type VARCHAR(30),
    return_date DATE,
    return_type VARCHAR(50),
    pending_dues NUMERIC(12,2) DEFAULT 0.00,
    damage_penalty NUMERIC(12,2) DEFAULT 0.00,
    remarks TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata'),
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata')
);

CREATE INDEX IF NOT EXISTS idx_july_dropoffs_vehicle ON public.july_vehicle_dropoffs (vehicle_number);
CREATE INDEX IF NOT EXISTS idx_july_dropoffs_date ON public.july_vehicle_dropoffs (return_date);

-- ------------------------------------------------------------------------------
-- 2. MASTER SINGLE SOURCE OF TRUTH: public.core_dropoffs
-- ------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.core_dropoffs (
    id BIGINT PRIMARY KEY,
    dropoff_id VARCHAR(50) UNIQUE NOT NULL,
    sheet_dropoff_id BIGINT,
    portal_dropoff_id INTEGER,
    return_date DATE NOT NULL,
    return_type VARCHAR(50) NOT NULL,
    driver_id VARCHAR(50),
    driver_name VARCHAR(255),
    driver_type VARCHAR(30),
    vehicle_number VARCHAR(20) NOT NULL,
    city VARCHAR(50) NOT NULL,
    negative_balance NUMERIC(12,2) DEFAULT 0.00,
    pending_dues NUMERIC(12,2) DEFAULT 0.00,
    damage_penalty NUMERIC(12,2) DEFAULT 0.00,
    total_liability NUMERIC(12,2) DEFAULT 0.00,
    remarks TEXT,
    data_source VARCHAR(50) NOT NULL,
    source_reference_id VARCHAR(100),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata'),
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata')
);

-- B-Tree Performance Indexes
CREATE INDEX IF NOT EXISTS idx_core_dropoffs_veh_date ON public.core_dropoffs (vehicle_number, return_date);
CREATE INDEX IF NOT EXISTS idx_core_dropoffs_vehicle ON public.core_dropoffs (vehicle_number);
CREATE INDEX IF NOT EXISTS idx_core_dropoffs_driver ON public.core_dropoffs (driver_id);
CREATE INDEX IF NOT EXISTS idx_core_dropoffs_return_date ON public.core_dropoffs (return_date);
CREATE INDEX IF NOT EXISTS idx_core_dropoffs_city ON public.core_dropoffs (city);
CREATE INDEX IF NOT EXISTS idx_core_dropoffs_data_source ON public.core_dropoffs (data_source);
CREATE INDEX IF NOT EXISTS idx_core_dropoffs_is_deleted ON public.core_dropoffs (is_deleted);
CREATE INDEX IF NOT EXISTS idx_core_dropoffs_dropoff_id ON public.core_dropoffs (dropoff_id);
CREATE INDEX IF NOT EXISTS idx_core_dropoffs_source_ref ON public.core_dropoffs (source_reference_id);
CREATE INDEX IF NOT EXISTS idx_core_dropoffs_sheet_id ON public.core_dropoffs (sheet_dropoff_id);
CREATE INDEX IF NOT EXISTS idx_core_dropoffs_portal_id ON public.core_dropoffs (portal_dropoff_id);
CREATE INDEX IF NOT EXISTS idx_core_dropoffs_return_type ON public.core_dropoffs (return_type);
CREATE INDEX IF NOT EXISTS idx_core_dropoffs_driver_type ON public.core_dropoffs (driver_type);

-- ------------------------------------------------------------------------------
-- 3. ACTIVE FILTERED VIEW: public.active_core_dropoffs
-- ------------------------------------------------------------------------------

CREATE OR REPLACE VIEW public.active_core_dropoffs AS
SELECT 
    id,
    dropoff_id,
    sheet_dropoff_id,
    portal_dropoff_id,
    return_date,
    return_type,
    driver_id,
    driver_name,
    driver_type,
    vehicle_number,
    city,
    negative_balance,
    pending_dues,
    damage_penalty,
    total_liability,
    remarks,
    data_source,
    source_reference_id,
    created_at,
    updated_at
FROM public.core_dropoffs
WHERE is_deleted = FALSE;

-- ------------------------------------------------------------------------------
-- 4. BUSINESS LOGIC HELPER FUNCTIONS
-- ------------------------------------------------------------------------------

-- 4.1 City Normalization Helper
CREATE OR REPLACE FUNCTION public.fn_normalize_dropoff_city(
    p_city TEXT,
    p_plate TEXT
) RETURNS VARCHAR(50) AS $$
DECLARE
    v_c TEXT;
    v_p TEXT;
BEGIN
    v_c := UPPER(TRIM(COALESCE(p_city, '')));
    v_p := UPPER(REGEXP_REPLACE(COALESCE(p_plate, ''), '[^A-Za-z0-9]', '', 'g'));

    -- Direct City Mappings
    IF v_c IN ('BLR', 'BANGALORE', 'BENGALURU') THEN
        RETURN 'Bengaluru';
    ELSIF v_c IN ('HYD', 'HYDERABAD') THEN
        RETURN 'Hyderabad';
    ELSIF v_c IN ('MUM', 'MUMBAI') THEN
        RETURN 'Mumbai';
    ELSIF v_c IN ('PUN', 'PUNE') THEN
        RETURN 'Pune';
    ELSIF v_c IN ('DEL', 'DELHI', 'NCR') THEN
        RETURN 'Delhi';
    END IF;

    -- Plate Prefix Inferences
    IF v_p LIKE 'KA%' THEN
        RETURN 'Bengaluru';
    ELSIF v_p LIKE 'TS%' OR v_p LIKE 'TG%' OR v_p LIKE 'AP%' THEN
        RETURN 'Hyderabad';
    ELSIF v_p LIKE 'MH%' THEN
        IF v_c LIKE '%PUNE%' THEN
            RETURN 'Pune';
        END IF;
        RETURN 'Mumbai';
    ELSIF v_p LIKE 'DL%' THEN
        RETURN 'Delhi';
    END IF;

    IF v_c != '' THEN
        RETURN INITCAP(v_c);
    END IF;

    RETURN 'Bengaluru';
END;
$$ LANGUAGE plpgsql IMMUTABLE;

-- 4.2 Driver Type Resolution Helper
CREATE OR REPLACE FUNCTION public.fn_resolve_driver_type(
    p_type TEXT,
    p_driver_id TEXT
) RETURNS VARCHAR(30) AS $$
DECLARE
    v_t TEXT;
    v_id TEXT;
BEGIN
    v_t := TRIM(COALESCE(p_type, ''));
    v_id := UPPER(TRIM(COALESCE(p_driver_id, '')));

    IF v_t != '' THEN
        RETURN INITCAP(v_t);
    END IF;

    IF v_id LIKE 'LETZ%IP%' THEN
        RETURN 'Operator';
    END IF;

    RETURN 'Individual';
END;
$$ LANGUAGE plpgsql IMMUTABLE;

-- 4.3 Liability Calculation Helper (Signed Polarity Contract: Liabilities are Negative)
CREATE OR REPLACE FUNCTION public.fn_calculate_dropoff_liability(
    p_neg NUMERIC,
    p_dues NUMERIC,
    p_dmg NUMERIC
) RETURNS NUMERIC(12,2) AS $$
DECLARE
    v_total NUMERIC(12,2);
BEGIN
    -- All liabilities standardized as signed negative deductions for Hisaab
    v_total := -1.0 * (
        ABS(COALESCE(p_neg, 0.00)) + 
        ABS(COALESCE(p_dues, 0.00)) + 
        ABS(COALESCE(p_dmg, 0.00))
    );
    RETURN v_total;
END;
$$ LANGUAGE plpgsql IMMUTABLE;

-- ------------------------------------------------------------------------------
-- 5. REAL-TIME ROW-LEVEL SYNCHRONIZATION TRIGGERS
-- ------------------------------------------------------------------------------

-- 5.1 Trigger Function: fn_sync_sheet_dropoffs()
CREATE OR REPLACE FUNCTION public.fn_sync_sheet_dropoffs()
RETURNS TRIGGER AS $$
DECLARE
    v_clean_veh VARCHAR(20);
    v_clean_city VARCHAR(50);
    v_clean_driver_id VARCHAR(50);
    v_driver_type VARCHAR(30);
    v_ref_id VARCHAR(50);
    v_existing_id BIGINT;
    v_existing_source VARCHAR(50);
    v_existing_ref VARCHAR(100);
    v_existing_portal_id INTEGER;
    v_existing_driver_id VARCHAR(50);
    v_final_driver_id VARCHAR(50);
    v_next_id BIGINT;
    v_neg_bal NUMERIC(12,2);
    v_total_liab NUMERIC(12,2);
BEGIN
    IF TG_OP = 'DELETE' THEN
        UPDATE public.core_dropoffs
        SET is_deleted = TRUE, 
            deleted_at = (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata'), 
            updated_at = (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata')
        WHERE sheet_dropoff_id = OLD.dropoff_id;
        RETURN OLD;
    END IF;

    v_clean_veh := UPPER(REGEXP_REPLACE(COALESCE(NEW.vehicle_number, ''), '[^A-Za-z0-9]', '', 'g'));
    
    -- Plate regex validation: ignore invalid plates
    IF v_clean_veh !~ '^[A-Z]{2}[0-9]{1,2}[A-Z]{0,3}[0-9]{4}$' THEN
        RETURN NEW;
    END IF;

    v_clean_city := public.fn_normalize_dropoff_city(NEW.city, v_clean_veh);
    v_clean_driver_id := COALESCE(NULLIF(TRIM(NEW.driver_id), ''), 'UNKNOWN_DRIVER');
    v_driver_type := public.fn_resolve_driver_type(NEW.driver_type, v_clean_driver_id);
    v_ref_id := COALESCE(NEW.dropoff_id::TEXT, NEW.source_row::TEXT);

    -- Signed liability polarity
    IF NEW.negative_balance IS NOT NULL THEN
        v_neg_bal := -1.0 * ABS(NEW.negative_balance);
    ELSE
        v_neg_bal := 0.00;
    END IF;

    -- Transactional advisory lock
    PERFORM pg_advisory_xact_lock(777444555);

    -- Seek existing record
    SELECT id, data_source, source_reference_id, portal_dropoff_id, driver_id
    INTO v_existing_id, v_existing_source, v_existing_ref, v_existing_portal_id, v_existing_driver_id
    FROM public.core_dropoffs
    WHERE sheet_dropoff_id = NEW.dropoff_id
       OR (
           vehicle_number = v_clean_veh 
           AND return_date = NEW.return_date
           AND (
               driver_id = v_clean_driver_id
               OR driver_id = 'UNKNOWN_DRIVER'
               OR v_clean_driver_id = 'UNKNOWN_DRIVER'
               OR (driver_id LIKE '%IP%' AND v_clean_driver_id LIKE '%' || SUBSTRING(driver_id FROM 8) || '%')
               OR (v_clean_driver_id LIKE '%IP%' AND driver_id LIKE '%' || SUBSTRING(v_clean_driver_id FROM 8) || '%')
           )
       )
    ORDER BY id DESC
    LIMIT 1;

    IF v_existing_id IS NOT NULL THEN
        -- Operator IP Priority Rule
        IF v_existing_driver_id LIKE '%IP%' AND v_clean_driver_id NOT LIKE '%IP%' THEN
            v_final_driver_id := v_existing_driver_id;
        ELSE
            v_final_driver_id := v_clean_driver_id;
        END IF;

        v_total_liab := public.fn_calculate_dropoff_liability(
            COALESCE(v_neg_bal, 0.00),
            (SELECT pending_dues FROM public.core_dropoffs WHERE id = v_existing_id),
            (SELECT damage_penalty FROM public.core_dropoffs WHERE id = v_existing_id)
        );

        UPDATE public.core_dropoffs
        SET
            sheet_dropoff_id = NEW.dropoff_id,
            vehicle_number = v_clean_veh,
            city = v_clean_city,
            return_date = NEW.return_date,
            return_type = COALESCE(NULLIF(NEW.return_type, ''), core_dropoffs.return_type),
            driver_id = v_final_driver_id,
            driver_name = COALESCE(NULLIF(NEW.driver_name, ''), core_dropoffs.driver_name),
            driver_type = v_driver_type,
            negative_balance = v_neg_bal,
            total_liability = v_total_liab,
            data_source = CASE WHEN v_existing_source = 'PORTAL_FORM' THEN 'MERGED' ELSE core_dropoffs.data_source END,
            source_reference_id = CASE 
                WHEN v_existing_portal_id IS NOT NULL 
                THEN v_ref_id || ',' || v_existing_portal_id::TEXT
                ELSE COALESCE(v_ref_id, core_dropoffs.source_reference_id)
            END,
            is_deleted = FALSE,
            deleted_at = NULL,
            updated_at = (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata')
        WHERE id = v_existing_id;
    ELSE
        SELECT COALESCE(MAX(id), 0) + 1 INTO v_next_id FROM public.core_dropoffs;
        v_total_liab := public.fn_calculate_dropoff_liability(v_neg_bal, 0.00, 0.00);

        INSERT INTO public.core_dropoffs (
            id,
            dropoff_id,
            sheet_dropoff_id,
            portal_dropoff_id,
            return_date,
            return_type,
            driver_id,
            driver_name,
            driver_type,
            vehicle_number,
            city,
            negative_balance,
            pending_dues,
            damage_penalty,
            total_liability,
            remarks,
            data_source,
            source_reference_id,
            is_deleted,
            created_at,
            updated_at
        ) VALUES (
            v_next_id,
            v_next_id::TEXT,
            NEW.dropoff_id,
            NULL,
            NEW.return_date,
            COALESCE(NULLIF(NEW.return_type, ''), 'Attrition'),
            v_clean_driver_id,
            COALESCE(NULLIF(NEW.driver_name, ''), 'Unknown Driver'),
            v_driver_type,
            v_clean_veh,
            v_clean_city,
            v_neg_bal,
            0.00,
            0.00,
            v_total_liab,
            NULL,
            'GOOGLE_SHEET',
            v_ref_id,
            FALSE,
            (COALESCE(NEW.created_at, CURRENT_TIMESTAMP) AT TIME ZONE 'Asia/Kolkata'),
            (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata')
        );
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_sheet_dropoffs_sync ON public.sheet_dropoffs;
CREATE TRIGGER trg_sheet_dropoffs_sync
AFTER INSERT OR UPDATE OR DELETE ON public.sheet_dropoffs
FOR EACH ROW EXECUTE FUNCTION public.fn_sync_sheet_dropoffs();

-- 5.2 Trigger Function: fn_sync_july_vehicle_dropoffs()
CREATE OR REPLACE FUNCTION public.fn_sync_july_vehicle_dropoffs()
RETURNS TRIGGER AS $$
DECLARE
    v_clean_veh VARCHAR(20);
    v_clean_city VARCHAR(50);
    v_clean_driver_id VARCHAR(50);
    v_driver_type VARCHAR(30);
    v_return_date DATE;
    v_pending_dues NUMERIC(12,2);
    v_damage_pen NUMERIC(12,2);
    v_total_liab NUMERIC(12,2);
    v_ref_id VARCHAR(50);
    v_existing_id BIGINT;
    v_existing_source VARCHAR(50);
    v_existing_ref VARCHAR(100);
    v_existing_sheet_id BIGINT;
    v_existing_driver_id VARCHAR(50);
    v_existing_return_type VARCHAR(50);
    v_existing_remarks TEXT;
    v_final_driver_id VARCHAR(50);
    v_combined_remarks TEXT;
    v_next_id BIGINT;
BEGIN
    IF TG_OP = 'DELETE' THEN
        UPDATE public.core_dropoffs
        SET is_deleted = TRUE, 
            deleted_at = (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata'), 
            updated_at = (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata')
        WHERE portal_dropoff_id = OLD.id;
        RETURN OLD;
    END IF;

    IF NEW.vehicle_number IS NOT NULL AND NEW.vehicle_number != '' THEN
        v_clean_veh := UPPER(REGEXP_REPLACE(NEW.vehicle_number, '[^A-Za-z0-9]', '', 'g'));
        
        -- Regex Gatekeeper: Ignore dummy/test plates
        IF v_clean_veh !~ '^[A-Z]{2}[0-9]{1,2}[A-Z]{0,3}[0-9]{4}$' THEN
            RETURN NEW;
        END IF;

        v_clean_city := public.fn_normalize_dropoff_city(NEW.city_name, v_clean_veh);
        v_clean_driver_id := COALESCE(NULLIF(TRIM(NEW.driver_id), ''), 'UNKNOWN_DRIVER');
        v_driver_type := public.fn_resolve_driver_type(COALESCE(NEW.driver_type, 'Individual'), v_clean_driver_id);
        v_ref_id := NEW.id::TEXT;
        
        v_return_date := COALESCE(
            CASE 
                WHEN NEW.return_date::TEXT ~ '^\d{4}-\d{2}-\d{2}' THEN NEW.return_date::DATE
                WHEN NEW.return_date::TEXT ~ '^\d{2}/\d{2}/\d{4}' THEN TO_DATE(NEW.return_date::TEXT, 'DD/MM/YYYY')
                ELSE NULL
            END,
            CURRENT_DATE
        );

        v_pending_dues := COALESCE(NEW.pending_dues, 0.00);
        v_damage_pen := COALESCE(NEW.damage_penalty, 0.00);

        -- Transactional advisory lock
        PERFORM pg_advisory_xact_lock(777444555);

        -- Seek existing record
        SELECT id, data_source, source_reference_id, sheet_dropoff_id, driver_id, return_type, remarks
        INTO v_existing_id, v_existing_source, v_existing_ref, v_existing_sheet_id, v_existing_driver_id, v_existing_return_type, v_existing_remarks
        FROM public.core_dropoffs
        WHERE portal_dropoff_id = NEW.id
           OR (
               vehicle_number = v_clean_veh 
               AND return_date = v_return_date
               AND (
                   driver_id = v_clean_driver_id
                   OR driver_id = 'UNKNOWN_DRIVER'
                   OR v_clean_driver_id = 'UNKNOWN_DRIVER'
                   OR (driver_id LIKE '%IP%' AND v_clean_driver_id LIKE '%' || SUBSTRING(driver_id FROM 8) || '%')
                   OR (v_clean_driver_id LIKE '%IP%' AND driver_id LIKE '%' || SUBSTRING(v_clean_driver_id FROM 8) || '%')
               )
           )
        ORDER BY id DESC
        LIMIT 1;

        IF v_existing_id IS NOT NULL THEN
            -- Operator IP Priority Rule
            IF v_clean_driver_id LIKE '%IP%' THEN
                v_final_driver_id := v_clean_driver_id;
            ELSIF v_existing_driver_id LIKE '%IP%' THEN
                v_final_driver_id := v_existing_driver_id;
            ELSE
                v_final_driver_id := COALESCE(NULLIF(v_clean_driver_id, 'UNKNOWN_DRIVER'), v_existing_driver_id);
            END IF;

            -- Concatenate Remarks
            IF NULLIF(TRIM(COALESCE(NEW.remarks, '')), '') IS NOT NULL THEN
                IF v_existing_remarks IS NOT NULL AND v_existing_remarks NOT LIKE '%' || NEW.remarks || '%' THEN
                    v_combined_remarks := v_existing_remarks || ' | Portal: ' || NEW.remarks;
                ELSE
                    v_combined_remarks := COALESCE(v_existing_remarks, 'Portal: ' || NEW.remarks);
                END IF;
            ELSE
                v_combined_remarks := v_existing_remarks;
            END IF;

            v_total_liab := public.fn_calculate_dropoff_liability(
                (SELECT negative_balance FROM public.core_dropoffs WHERE id = v_existing_id),
                v_pending_dues,
                v_damage_pen
            );

            UPDATE public.core_dropoffs
            SET
                portal_dropoff_id = NEW.id,
                city = COALESCE(NULLIF(v_clean_city, ''), core_dropoffs.city),
                driver_name = COALESCE(NULLIF(NEW.driver_name, ''), core_dropoffs.driver_name),
                driver_id = v_final_driver_id,
                driver_type = COALESCE(NULLIF(v_driver_type, ''), core_dropoffs.driver_type),
                return_type = COALESCE(v_existing_return_type, NULLIF(NEW.return_type, ''), core_dropoffs.return_type),
                pending_dues = v_pending_dues,
                damage_penalty = v_damage_pen,
                total_liability = v_total_liab,
                remarks = v_combined_remarks,
                data_source = CASE WHEN v_existing_source = 'GOOGLE_SHEET' THEN 'MERGED' ELSE 'PORTAL_FORM' END,
                source_reference_id = CASE 
                    WHEN v_existing_sheet_id IS NOT NULL 
                    THEN v_existing_sheet_id::TEXT || ',' || v_ref_id
                    ELSE COALESCE(v_existing_ref, v_ref_id)
                END,
                is_deleted = FALSE,
                deleted_at = NULL,
                updated_at = (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata')
            WHERE id = v_existing_id;
        ELSE
            SELECT COALESCE(MAX(id), 0) + 1 INTO v_next_id FROM public.core_dropoffs;
            v_total_liab := public.fn_calculate_dropoff_liability(0.00, v_pending_dues, v_damage_pen);

            INSERT INTO public.core_dropoffs (
                id,
                dropoff_id,
                sheet_dropoff_id,
                portal_dropoff_id,
                return_date,
                return_type,
                driver_id,
                driver_name,
                driver_type,
                vehicle_number,
                city,
                negative_balance,
                pending_dues,
                damage_penalty,
                total_liability,
                remarks,
                data_source,
                source_reference_id,
                is_deleted,
                created_at,
                updated_at
            ) VALUES (
                v_next_id,
                v_next_id::TEXT,
                NULL,
                NEW.id,
                v_return_date,
                COALESCE(NULLIF(NEW.return_type, ''), 'Attrition'),
                v_clean_driver_id,
                COALESCE(NULLIF(NEW.driver_name, ''), 'Unknown Driver'),
                v_driver_type,
                v_clean_veh,
                v_clean_city,
                0.00,
                v_pending_dues,
                v_damage_pen,
                v_total_liab,
                CASE WHEN NEW.remarks IS NOT NULL THEN 'Portal: ' || NEW.remarks ELSE NULL END,
                'PORTAL_FORM',
                v_ref_id,
                FALSE,
                (COALESCE(NEW.created_at, CURRENT_TIMESTAMP) AT TIME ZONE 'Asia/Kolkata'),
                (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata')
            );
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'july_vehicle_dropoffs') THEN
        DROP TRIGGER IF EXISTS trg_july_vehicle_dropoffs_sync ON public.july_vehicle_dropoffs;
        CREATE TRIGGER trg_july_vehicle_dropoffs_sync
        AFTER INSERT OR UPDATE OR DELETE ON public.july_vehicle_dropoffs
        FOR EACH ROW EXECUTE FUNCTION public.fn_sync_july_vehicle_dropoffs();
    END IF;
END $$;

-- ------------------------------------------------------------------------------
-- 6. FULL REFRESH STORED PROCEDURE: refresh_core_dropoffs()
-- ------------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.refresh_core_dropoffs()
RETURNS INTEGER AS $$
DECLARE
    r RECORD;
    p RECORD;
    v_clean_veh VARCHAR(20);
    v_clean_city VARCHAR(50);
    v_clean_driver_id VARCHAR(50);
    v_driver_type VARCHAR(30);
    v_neg_bal NUMERIC(12,2);
    v_total_liab NUMERIC(12,2);
    v_ref_id VARCHAR(50);
    v_next_id BIGINT;
    v_existing_id BIGINT;
    v_existing_source VARCHAR(50);
    v_existing_ref VARCHAR(100);
    v_existing_sheet_id BIGINT;
    v_existing_driver_id VARCHAR(50);
    v_existing_return_type VARCHAR(50);
    v_existing_remarks TEXT;
    v_final_driver_id VARCHAR(50);
    v_combined_remarks TEXT;
    v_inserted_count INTEGER := 0;
BEGIN
    PERFORM pg_advisory_xact_lock(777444555);

    -- Step 6.1: Sync all Google Sheet records
    FOR r IN 
        SELECT * FROM public.sheet_dropoffs 
        ORDER BY dropoff_id ASC
    LOOP
        v_clean_veh := UPPER(REGEXP_REPLACE(COALESCE(r.vehicle_number, ''), '[^A-Za-z0-9]', '', 'g'));
        
        -- Skip invalid plates
        IF v_clean_veh !~ '^[A-Z]{2}[0-9]{1,2}[A-Z]{0,3}[0-9]{4}$' THEN
            CONTINUE;
        END IF;

        v_clean_city := public.fn_normalize_dropoff_city(r.city, v_clean_veh);
        v_clean_driver_id := COALESCE(NULLIF(TRIM(r.driver_id), ''), 'UNKNOWN_DRIVER');
        v_driver_type := public.fn_resolve_driver_type(r.driver_type, v_clean_driver_id);
        v_ref_id := r.dropoff_id::TEXT;

        IF r.negative_balance IS NOT NULL THEN
            v_neg_bal := -1.0 * ABS(r.negative_balance);
        ELSE
            v_neg_bal := 0.00;
        END IF;

        -- Seek existing record
        SELECT id, data_source, source_reference_id, driver_id
        INTO v_existing_id, v_existing_source, v_existing_ref, v_existing_driver_id
        FROM public.core_dropoffs
        WHERE sheet_dropoff_id = r.dropoff_id
           OR (
               vehicle_number = v_clean_veh 
               AND return_date = r.return_date
               AND (
                   driver_id = v_clean_driver_id
                   OR driver_id = 'UNKNOWN_DRIVER'
                   OR v_clean_driver_id = 'UNKNOWN_DRIVER'
                   OR (driver_id LIKE '%IP%' AND v_clean_driver_id LIKE '%' || SUBSTRING(driver_id FROM 8) || '%')
                   OR (v_clean_driver_id LIKE '%IP%' AND driver_id LIKE '%' || SUBSTRING(v_clean_driver_id FROM 8) || '%')
               )
           )
        ORDER BY id DESC
        LIMIT 1;

        IF v_existing_id IS NOT NULL THEN
            IF v_existing_driver_id LIKE '%IP%' AND v_clean_driver_id NOT LIKE '%IP%' THEN
                v_final_driver_id := v_existing_driver_id;
            ELSE
                v_final_driver_id := v_clean_driver_id;
            END IF;

            v_total_liab := public.fn_calculate_dropoff_liability(
                v_neg_bal,
                (SELECT pending_dues FROM public.core_dropoffs WHERE id = v_existing_id),
                (SELECT damage_penalty FROM public.core_dropoffs WHERE id = v_existing_id)
            );

            UPDATE public.core_dropoffs
            SET
                sheet_dropoff_id = r.dropoff_id,
                vehicle_number = v_clean_veh,
                city = v_clean_city,
                return_date = r.return_date,
                return_type = COALESCE(NULLIF(r.return_type, ''), core_dropoffs.return_type),
                driver_id = v_final_driver_id,
                driver_name = COALESCE(NULLIF(r.driver_name, ''), core_dropoffs.driver_name),
                driver_type = v_driver_type,
                negative_balance = v_neg_bal,
                total_liability = v_total_liab,
                data_source = CASE WHEN v_existing_source = 'PORTAL_FORM' THEN 'MERGED' ELSE core_dropoffs.data_source END,
                source_reference_id = COALESCE(v_ref_id, core_dropoffs.source_reference_id),
                is_deleted = FALSE,
                deleted_at = NULL,
                updated_at = (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata')
            WHERE id = v_existing_id;
        ELSE
            SELECT COALESCE(MAX(id), 0) + 1 INTO v_next_id FROM public.core_dropoffs;
            v_total_liab := public.fn_calculate_dropoff_liability(v_neg_bal, 0.00, 0.00);

            INSERT INTO public.core_dropoffs (
                id,
                dropoff_id,
                sheet_dropoff_id,
                portal_dropoff_id,
                return_date,
                return_type,
                driver_id,
                driver_name,
                driver_type,
                vehicle_number,
                city,
                negative_balance,
                pending_dues,
                damage_penalty,
                total_liability,
                remarks,
                data_source,
                source_reference_id,
                is_deleted,
                created_at,
                updated_at
            ) VALUES (
                v_next_id,
                v_next_id::TEXT,
                r.dropoff_id,
                NULL,
                r.return_date,
                COALESCE(NULLIF(r.return_type, ''), 'Attrition'),
                v_clean_driver_id,
                COALESCE(NULLIF(r.driver_name, ''), 'Unknown Driver'),
                v_driver_type,
                v_clean_veh,
                v_clean_city,
                v_neg_bal,
                0.00,
                0.00,
                v_total_liab,
                NULL,
                'GOOGLE_SHEET',
                v_ref_id,
                FALSE,
                (COALESCE(r.created_at, CURRENT_TIMESTAMP) AT TIME ZONE 'Asia/Kolkata'),
                (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata')
            );
            v_inserted_count := v_inserted_count + 1;
        END IF;
    END LOOP;

    -- Step 6.2: Ingest & Merge from july_vehicle_dropoffs
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'july_vehicle_dropoffs') THEN
        FOR p IN 
            SELECT * FROM public.july_vehicle_dropoffs 
            ORDER BY id ASC
        LOOP
            v_clean_veh := UPPER(REGEXP_REPLACE(COALESCE(p.vehicle_number, ''), '[^A-Za-z0-9]', '', 'g'));
            
            -- Skip invalid plates
            IF v_clean_veh !~ '^[A-Z]{2}[0-9]{1,2}[A-Z]{0,3}[0-9]{4}$' THEN
                CONTINUE;
            END IF;

            v_clean_city := public.fn_normalize_dropoff_city(p.city_name, v_clean_veh);
            v_clean_driver_id := COALESCE(NULLIF(TRIM(p.driver_id), ''), 'UNKNOWN_DRIVER');
            v_driver_type := public.fn_resolve_driver_type(COALESCE(p.driver_type, 'Individual'), v_clean_driver_id);

            -- Seek existing record
            SELECT id, data_source, source_reference_id, sheet_dropoff_id, driver_id, return_type, remarks
            INTO v_existing_id, v_existing_source, v_existing_ref, v_existing_sheet_id, v_existing_driver_id, v_existing_return_type, v_existing_remarks
            FROM public.core_dropoffs
            WHERE portal_dropoff_id = p.id
               OR (
                   vehicle_number = v_clean_veh 
                   AND return_date = p.return_date
                   AND (
                       driver_id = v_clean_driver_id
                       OR driver_id = 'UNKNOWN_DRIVER'
                       OR v_clean_driver_id = 'UNKNOWN_DRIVER'
                       OR (driver_id LIKE '%IP%' AND v_clean_driver_id LIKE '%' || SUBSTRING(driver_id FROM 8) || '%')
                       OR (v_clean_driver_id LIKE '%IP%' AND driver_id LIKE '%' || SUBSTRING(v_clean_driver_id FROM 8) || '%')
                   )
               )
            ORDER BY id DESC
            LIMIT 1;

            IF v_existing_id IS NOT NULL THEN
                IF v_clean_driver_id LIKE '%IP%' THEN
                    v_final_driver_id := v_clean_driver_id;
                ELSIF v_existing_driver_id LIKE '%IP%' THEN
                    v_final_driver_id := v_existing_driver_id;
                ELSE
                    v_final_driver_id := COALESCE(NULLIF(v_clean_driver_id, 'UNKNOWN_DRIVER'), v_existing_driver_id);
                END IF;

                IF NULLIF(TRIM(COALESCE(p.remarks, '')), '') IS NOT NULL THEN
                    IF v_existing_remarks IS NOT NULL AND v_existing_remarks NOT LIKE '%' || p.remarks || '%' THEN
                        v_combined_remarks := v_existing_remarks || ' | Portal: ' || p.remarks;
                    ELSE
                        v_combined_remarks := COALESCE(v_existing_remarks, 'Portal: ' || p.remarks);
                    END IF;
                ELSE
                    v_combined_remarks := v_existing_remarks;
                END IF;

                v_total_liab := public.fn_calculate_dropoff_liability(
                    (SELECT negative_balance FROM public.core_dropoffs WHERE id = v_existing_id),
                    COALESCE(p.pending_dues, 0.00),
                    COALESCE(p.damage_penalty, 0.00)
                );

                v_ref_id := p.id::TEXT;

                UPDATE public.core_dropoffs
                SET
                    portal_dropoff_id = p.id,
                    city = COALESCE(NULLIF(v_clean_city, ''), core_dropoffs.city),
                    driver_name = COALESCE(NULLIF(p.driver_name, ''), core_dropoffs.driver_name),
                    driver_id = v_final_driver_id,
                    driver_type = COALESCE(NULLIF(v_driver_type, ''), core_dropoffs.driver_type),
                    pending_dues = COALESCE(p.pending_dues, 0.00),
                    damage_penalty = COALESCE(p.damage_penalty, 0.00),
                    total_liability = v_total_liab,
                    remarks = v_combined_remarks,
                    data_source = CASE WHEN v_existing_source = 'GOOGLE_SHEET' THEN 'MERGED' ELSE 'PORTAL_FORM' END,
                    source_reference_id = CASE 
                        WHEN v_existing_sheet_id IS NOT NULL 
                        THEN v_existing_sheet_id::TEXT || ',' || v_ref_id
                        ELSE COALESCE(v_existing_ref, v_ref_id)
                    END,
                    is_deleted = FALSE,
                    deleted_at = NULL,
                    updated_at = (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata')
                WHERE id = v_existing_id;
            ELSE
                SELECT COALESCE(MAX(id), 0) + 1 INTO v_next_id FROM public.core_dropoffs;
                v_total_liab := public.fn_calculate_dropoff_liability(0.00, COALESCE(p.pending_dues, 0.00), COALESCE(p.damage_penalty, 0.00));

                INSERT INTO public.core_dropoffs (
                    id,
                    dropoff_id,
                    sheet_dropoff_id,
                    portal_dropoff_id,
                    return_date,
                    return_type,
                    driver_id,
                    driver_name,
                    driver_type,
                    vehicle_number,
                    city,
                    negative_balance,
                    pending_dues,
                    damage_penalty,
                    total_liability,
                    remarks,
                    data_source,
                    source_reference_id,
                    is_deleted,
                    created_at,
                    updated_at
                ) VALUES (
                    v_next_id,
                    v_next_id::TEXT,
                    NULL,
                    p.id,
                    p.return_date,
                    COALESCE(NULLIF(p.return_type, ''), 'Attrition'),
                    v_clean_driver_id,
                    COALESCE(NULLIF(p.driver_name, ''), 'Unknown Driver'),
                    v_driver_type,
                    v_clean_veh,
                    v_clean_city,
                    0.00,
                    COALESCE(p.pending_dues, 0.00),
                    COALESCE(p.damage_penalty, 0.00),
                    v_total_liab,
                    CASE WHEN p.remarks IS NOT NULL THEN 'Portal: ' || p.remarks ELSE NULL END,
                    'PORTAL_FORM',
                    p.id::TEXT,
                    FALSE,
                    (COALESCE(p.created_at, CURRENT_TIMESTAMP) AT TIME ZONE 'Asia/Kolkata'),
                    (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata')
                );
                v_inserted_count := v_inserted_count + 1;
            END IF;
        END LOOP;
    END IF;

    RETURN v_inserted_count;
END;
$$ LANGUAGE plpgsql;

-- ------------------------------------------------------------------------------
-- 7. METADATA & SCHEMA COMMENTS
-- ------------------------------------------------------------------------------

COMMENT ON TABLE public.core_dropoffs IS 'Consolidated Master Single Source of Truth for vehicle returns and driver liabilities.';
COMMENT ON COLUMN public.core_dropoffs.id IS 'Gapless continuous primary key manually assigned via MAX(id) + 1 with advisory lock 777444555.';
COMMENT ON COLUMN public.core_dropoffs.dropoff_id IS 'Plain numerical business identifier matching id::TEXT (e.g. 1578).';
COMMENT ON COLUMN public.core_dropoffs.sheet_dropoff_id IS 'Foreign key reference linking directly to public.sheet_dropoffs(dropoff_id).';
COMMENT ON COLUMN public.core_dropoffs.portal_dropoff_id IS 'Foreign key reference linking directly to public.july_vehicle_dropoffs(id).';
COMMENT ON COLUMN public.core_dropoffs.return_date IS 'Standardized ISO calendar date when vehicle was returned to hub custody.';
COMMENT ON COLUMN public.core_dropoffs.return_type IS 'Operational classification (Attrition, Repair and Maintenance, Force Recovery).';
COMMENT ON COLUMN public.core_dropoffs.driver_id IS 'Identifier linking driver to core_partner_onboarding.';
COMMENT ON COLUMN public.core_dropoffs.driver_name IS 'Sanitized driver full name.';
COMMENT ON COLUMN public.core_dropoffs.driver_type IS 'Driver classification (Individual or Operator).';
COMMENT ON COLUMN public.core_dropoffs.vehicle_number IS 'Normalized uppercase alphanumeric registration plate.';
COMMENT ON COLUMN public.core_dropoffs.city IS 'Canonical city name (Bengaluru, Hyderabad, Mumbai, Pune, Delhi).';
COMMENT ON COLUMN public.core_dropoffs.negative_balance IS 'Signed negative liability from Ola/Uber balances.';
COMMENT ON COLUMN public.core_dropoffs.pending_dues IS 'Signed negative liability from unpaid vehicle rent/fastag.';
COMMENT ON COLUMN public.core_dropoffs.damage_penalty IS 'Signed negative liability assessed for vehicle body/interior damage.';
COMMENT ON COLUMN public.core_dropoffs.total_liability IS 'Combined signed driver deduction: negative_balance + pending_dues + damage_penalty.';
COMMENT ON COLUMN public.core_dropoffs.remarks IS 'Inspection notes and handover comments.';
COMMENT ON COLUMN public.core_dropoffs.data_source IS 'Provenance of dropoff record: GOOGLE_SHEET, PORTAL_FORM, or MERGED.';
COMMENT ON COLUMN public.core_dropoffs.source_reference_id IS 'Plain numerical pointer back to source row in sheet_dropoffs or july_vehicle_dropoffs.';
COMMENT ON COLUMN public.core_dropoffs.is_deleted IS 'Soft-delete flag protecting historical ledger entries.';
COMMENT ON COLUMN public.core_dropoffs.deleted_at IS 'IST timestamp when row was soft-deleted.';
COMMENT ON COLUMN public.core_dropoffs.created_at IS 'IST timestamp when record was created.';
COMMENT ON COLUMN public.core_dropoffs.updated_at IS 'IST timestamp when record was last updated.';

COMMENT ON VIEW public.active_core_dropoffs IS 'Filtered view of active vehicle drop-offs (WHERE is_deleted = FALSE).';

-- ------------------------------------------------------------------------------
-- 8. PRODUCTION VERIFICATION & AUDIT QUERIES
-- ------------------------------------------------------------------------------

-- Query 1: Total and Active Record Counts
SELECT 
    COUNT(*) AS total_rows,
    COUNT(*) FILTER (WHERE is_deleted = FALSE) AS active_rows,
    COUNT(*) FILTER (WHERE is_deleted = TRUE) AS soft_deleted_rows
FROM public.core_dropoffs;

-- Query 2: Gapless 1..N ID Continuity Check
SELECT 
    MIN(id) AS min_id,
    MAX(id) AS max_id,
    COUNT(*) AS total_records,
    (SELECT COUNT(*) FROM generate_series(1, (SELECT MAX(id) FROM public.core_dropoffs)) s(i) 
     LEFT JOIN public.core_dropoffs c ON s.i = c.id WHERE c.id IS NULL) AS sequence_gaps
FROM public.core_dropoffs;

-- Query 3: Plain Numerical ID Validation (Zero String Prefixes)
SELECT COUNT(*) AS invalid_dropoff_ids
FROM public.core_dropoffs
WHERE dropoff_id !~ '^[0-9]+$';

-- Query 4: Polarity and Financial Balance Validation
SELECT COUNT(*) AS liability_violations
FROM public.core_dropoffs
WHERE total_liability > 0 
   OR ABS(total_liability - (-1.0 * (ABS(COALESCE(negative_balance, 0.00)) + ABS(COALESCE(pending_dues, 0.00)) + ABS(COALESCE(damage_penalty, 0.00))))) > 0.01;
