-- ============================================================================
-- DEPRECATED: TRIGGERS HAVE BEEN REPLACED BY PG_CRON STORED PROCEDURES
-- ============================================================================
-- NOTE: In accordance with the LetzRyd architectural audit:
-- ALL triggers attached to upstream core tables (core_adjustments, core_challans,
-- core_gps, core_ola_daily, core_ola_weekly) have been permanently DROPPED.
-- 
-- Rationale:
-- 1. Upstream Data Ingestion Protection: Triggers locked ingestion processes and
--    caused cascading deadlocks and ingestion failures.
-- 2. Performance & Idempotency: Real-time calculation on high-volume feeds degraded
--    throughput by up to 20x.
-- 
-- New Automation Architecture:
-- Weekly settlement calculation is 100% downstream and decoupled:
-- 1. Stored Procedure: public.sp_sync_hisaab_vehicle_weekly() (see procedures.sql)
-- 2. Automation: pg_cron job 'hisaab-vehicle-weekly-sync' at 03:00 daily (see cron.sql)
-- ============================================================================
