-- ==============================================================================
-- LETZRYD VEHICLE DROPOFF ENGINE - POSTGRESQL STAGING SCHEMA DDL
-- ==============================================================================
-- Target Database: postgres
-- Target Schema  : public
-- Staging Table  : public.sheet_dropoffs
-- Source System  : Google Sheets ('dropoffs_form', tab: 'sheet_dropoffs')
-- Host           : YOUR_DB_HOST_HERE:5432
-- Description    : DDL and operational verification queries for the raw vehicle
--                  dropoff staging table. Decoupled strictly from core_dropoffs
--                  (which resides in Vehicle Dropoff Final Table).
-- ==============================================================================

-- ------------------------------------------------------------------------------
-- 1. TABLE DEFINITION: public.sheet_dropoffs (Raw Staging Table)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.sheet_dropoffs (
    dropoff_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_row INTEGER UNIQUE,
    return_date DATE NOT NULL,
    return_type VARCHAR(50) NOT NULL,
    driver_id VARCHAR(50),
    driver_name VARCHAR(255),
    driver_type VARCHAR(30) DEFAULT 'Individual',
    vehicle_number VARCHAR(20) NOT NULL,
    city VARCHAR(50) NOT NULL,
    negative_balance NUMERIC(12,2) DEFAULT 0.00,
    sync_status VARCHAR(20) DEFAULT 'SYNCED',
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata'),
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata')
);

-- ------------------------------------------------------------------------------
-- 2. B-TREE INDEXES FOR OPTIMIZED QUERYING & INGESTION
-- ------------------------------------------------------------------------------
-- Index on vehicle registration number for fleet lookups
CREATE INDEX IF NOT EXISTS idx_sheet_dropoffs_vehicle 
    ON public.sheet_dropoffs (vehicle_number);

-- Index on return date for temporal range filtering and window sync
CREATE INDEX IF NOT EXISTS idx_sheet_dropoffs_return_date 
    ON public.sheet_dropoffs (return_date);

-- Index on driver identifier for hisaab and driver ledger association
CREATE INDEX IF NOT EXISTS idx_sheet_dropoffs_driver 
    ON public.sheet_dropoffs (driver_id);

-- Index on operating hub/city for regional analytics
CREATE INDEX IF NOT EXISTS idx_sheet_dropoffs_city 
    ON public.sheet_dropoffs (city);

-- Index on return classification (Attrition, Repair and Maintenance, Force Recovery)
CREATE INDEX IF NOT EXISTS idx_sheet_dropoffs_return_type 
    ON public.sheet_dropoffs (return_type);

-- Unique index support on source row for idempotent upserts
CREATE INDEX IF NOT EXISTS idx_sheet_dropoffs_source_row 
    ON public.sheet_dropoffs (source_row);

-- Composite index for vehicle return history verification
CREATE INDEX IF NOT EXISTS idx_sheet_dropoffs_veh_date 
    ON public.sheet_dropoffs (vehicle_number, return_date);

-- Index on sync status for operational catch-up queries
CREATE INDEX IF NOT EXISTS idx_sheet_dropoffs_sync_status 
    ON public.sheet_dropoffs (sync_status);

-- ------------------------------------------------------------------------------
-- 3. ZERO-BURN SEQUENCE CTE UPSERT QUERY (JDBC PREPARED STATEMENT FORMAT)
-- ------------------------------------------------------------------------------
-- Root Cause Addressed:
-- Standard INSERT INTO ... ON CONFLICT (source_row) DO UPDATE advances the
-- underlying IDENTITY sequence (nextval) even when a conflict occurs and an
-- UPDATE is performed. Over frequent 1-minute catch-up syncs, millions of
-- sequence IDs are burned without new rows being inserted.
--
-- Architectural Solution:
-- The Zero-Burn CTE isolates the incoming record into an in-memory row.
-- The `upd` CTE attempts to UPDATE an existing record matching source_row.
-- If an update succeeds, the RETURNING clause captures the dropoff_id.
-- The subsequent INSERT statement executes ONLY when NOT EXISTS (SELECT 1 FROM upd).
-- Thus, nextval() is never evaluated during updates, preserving sequence continuity.
--
-- JDBC Parameter Index Mapping:
-- ? 1: source_row       (INTEGER)
-- ? 2: return_date      (DATE, format: 'YYYY-MM-DD')
-- ? 3: return_type      (VARCHAR)
-- ? 4: driver_id        (VARCHAR)
-- ? 5: driver_name      (VARCHAR)
-- ? 6: driver_type      (VARCHAR)
-- ? 7: vehicle_number   (VARCHAR)
-- ? 8: city             (VARCHAR)
-- ? 9: negative_balance (NUMERIC(12,2))
-- ------------------------------------------------------------------------------

/*
WITH incoming AS (
    SELECT 
        CAST(? AS integer) AS src_row,
        CAST(? AS date) AS ret_date,
        CAST(? AS varchar) AS ret_type,
        CAST(? AS varchar) AS drv_id,
        CAST(? AS varchar) AS drv_name,
        CAST(? AS varchar) AS drv_type,
        CAST(? AS varchar) AS veh_num,
        CAST(? AS varchar) AS city_name,
        CAST(? AS numeric) AS neg_bal
),
upd AS (
    UPDATE public.sheet_dropoffs s
    SET 
        return_date = i.ret_date,
        return_type = i.ret_type,
        driver_id = i.drv_id,
        driver_name = i.drv_name,
        driver_type = i.drv_type,
        vehicle_number = i.veh_num,
        city = i.city_name,
        negative_balance = i.neg_bal,
        sync_status = 'SYNCED',
        updated_at = (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata')
    FROM incoming i
    WHERE s.source_row = i.src_row
    RETURNING s.dropoff_id
)
INSERT INTO public.sheet_dropoffs (
    source_row, return_date, return_type, driver_id, driver_name,
    driver_type, vehicle_number, city, negative_balance, sync_status,
    created_at, updated_at
)
SELECT 
    i.src_row, i.ret_date, i.ret_type, i.drv_id, i.drv_name,
    i.drv_type, i.veh_num, i.city_name, i.neg_bal, 'SYNCED',
    (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata'),
    (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata')
FROM incoming i
WHERE NOT EXISTS (SELECT 1 FROM upd);
*/

-- ------------------------------------------------------------------------------
-- 4. OPERATIONAL VERIFICATION & DIAGNOSTIC QUERIES
-- ------------------------------------------------------------------------------

-- 4.1 Sequence State and last_value Inspection
-- Verifies that the underlying identity sequence matches row count without runaway sequence burning.
SELECT 
    sequence_schema,
    sequence_name,
    data_type,
    start_value,
    minimum_value,
    maximum_value,
    increment,
    cycle_option
FROM information_schema.sequences
WHERE sequence_name LIKE 'sheet_dropoffs_dropoff_id_seq%';

SELECT 
    schemaname,
    sequencename,
    last_value,
    is_called,
    log_cnt
FROM pg_sequences
WHERE sequencename = 'sheet_dropoffs_dropoff_id_seq';

-- 4.2 Sequence Gap Detection Query
-- Identifies any holes in the dropoff_id sequence to confirm Zero-Burn CTE operation.
SELECT 
    dropoff_id + 1 AS gap_start,
    next_id - 1 AS gap_end,
    (next_id - dropoff_id - 1) AS gap_size
FROM (
    SELECT 
        dropoff_id, 
        LEAD(dropoff_id) OVER (ORDER BY dropoff_id) AS next_id
    FROM public.sheet_dropoffs
) sub
WHERE next_id > dropoff_id + 1;

-- 4.3 Sequence Gapless Verification Summary
SELECT 
    COUNT(*) AS total_rows,
    MIN(dropoff_id) AS min_id,
    MAX(dropoff_id) AS max_id,
    (MAX(dropoff_id) - MIN(dropoff_id) + 1) AS expected_span,
    (MAX(dropoff_id) - MIN(dropoff_id) + 1) - COUNT(*) AS gap_count,
    CASE 
        WHEN (MAX(dropoff_id) - MIN(dropoff_id) + 1) = COUNT(*) 
        THEN 'PASSED: Perfectly Continuous Gapless Sequence'
        ELSE 'NOTICE: Sequence gaps exist'
    END AS status_check
FROM public.sheet_dropoffs;

-- 4.4 Duplicate Check on source_row
-- Ensures source_row constraint maintains 1:1 mapping with spreadsheet rows.
SELECT 
    source_row, 
    COUNT(*) AS duplicate_count
FROM public.sheet_dropoffs
WHERE source_row IS NOT NULL
GROUP BY source_row
HAVING COUNT(*) > 1;

-- 4.5 Multi-Event Analysis (Same Vehicle, Same Date)
-- Detects vehicle returns occurring multiple times on the same date.
-- In sheet_dropoffs, these are legitimate separate physical events tracked by distinct source_row.
SELECT 
    vehicle_number, 
    return_date, 
    COUNT(*) AS event_count,
    ARRAY_AGG(source_row ORDER BY source_row) AS source_rows,
    ARRAY_AGG(dropoff_id ORDER BY dropoff_id) AS dropoff_ids,
    SUM(negative_balance) AS total_negative_balance
FROM public.sheet_dropoffs
WHERE is_deleted = FALSE
GROUP BY vehicle_number, return_date
HAVING COUNT(*) > 1
ORDER BY event_count DESC, vehicle_number ASC;

-- 4.6 Ingestion Sync Status and Financial Liability Distribution
SELECT 
    sync_status,
    COUNT(*) AS total_records,
    COUNT(DISTINCT vehicle_number) AS unique_vehicles,
    COUNT(DISTINCT driver_id) AS unique_drivers,
    MIN(return_date) AS earliest_return_date,
    MAX(return_date) AS latest_return_date,
    SUM(negative_balance) AS net_negative_balance,
    COUNT(CASE WHEN negative_balance < 0 THEN 1 END) AS negative_balance_rows,
    COUNT(CASE WHEN negative_balance > 0 THEN 1 END) AS positive_balance_anomalies,
    COUNT(CASE WHEN negative_balance = 0 THEN 1 END) AS zero_balance_rows
FROM public.sheet_dropoffs
GROUP BY sync_status;

-- 4.7 City and Return Type Distribution Summary
SELECT 
    city,
    return_type,
    COUNT(*) AS total_dropoffs,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (), 2) AS pct_share
FROM public.sheet_dropoffs
GROUP BY city, return_type
ORDER BY city ASC, total_dropoffs DESC;

-- 4.8 Vehicle Plate Format Hygiene Audit
-- Verifies that stored vehicle numbers strictly adhere to the standard Indian format.
SELECT 
    vehicle_number,
    COUNT(*) AS occurrences
FROM public.sheet_dropoffs
WHERE vehicle_number !~ '^[A-Z]{2}[0-9]{1,2}[A-Z]{0,3}[0-9]{4}$'
GROUP BY vehicle_number;

-- ------------------------------------------------------------------------------
-- 5. TABLE & COLUMN DOCUMENTATION COMMENTS
-- ------------------------------------------------------------------------------
COMMENT ON TABLE public.sheet_dropoffs IS 
    'Raw staging table ingested directly from Google Sheets dropoffs_form (tab: sheet_dropoffs).';

COMMENT ON COLUMN public.sheet_dropoffs.dropoff_id IS 
    'Primary key identity generated by default as identity.';

COMMENT ON COLUMN public.sheet_dropoffs.source_row IS 
    'Physical row index in the source Google Sheet to ensure idempotent updates.';

COMMENT ON COLUMN public.sheet_dropoffs.return_date IS 
    'Standardized return date (YYYY-MM-DD) normalized in Asia/Kolkata timezone.';

COMMENT ON COLUMN public.sheet_dropoffs.return_type IS 
    'Reason or category for vehicle return (e.g., Attrition, Repair and Maintenance).';

COMMENT ON COLUMN public.sheet_dropoffs.driver_id IS 
    'Operator or driver alphanumeric identifier.';

COMMENT ON COLUMN public.sheet_dropoffs.driver_name IS 
    'Full name of the returning driver.';

COMMENT ON COLUMN public.sheet_dropoffs.driver_type IS 
    'Classification of driver: Individual or Operator.';

COMMENT ON COLUMN public.sheet_dropoffs.vehicle_number IS 
    'Sanitized uppercase alphanumeric Indian vehicle registration number.';

COMMENT ON COLUMN public.sheet_dropoffs.city IS 
    'Standardized operating hub name (e.g., Bengaluru, Hyderabad, Mumbai, Pune, Delhi).';

COMMENT ON COLUMN public.sheet_dropoffs.negative_balance IS 
    'Driver liabilities recorded as negative numerical balance (e.g., -500.00).';

COMMENT ON COLUMN public.sheet_dropoffs.sync_status IS 
    'Synchronization state from the Google Apps Script engine (SYNCED, PENDING).';

COMMENT ON COLUMN public.sheet_dropoffs.is_deleted IS 
    'Soft deletion flag for records removed from the source spreadsheet.';

COMMENT ON COLUMN public.sheet_dropoffs.deleted_at IS 
    'Timestamp when record was marked as deleted in Indian Standard Time.';

COMMENT ON COLUMN public.sheet_dropoffs.created_at IS 
    'Timestamp of initial ingestion in Indian Standard Time (Asia/Kolkata).';

COMMENT ON COLUMN public.sheet_dropoffs.updated_at IS 
    'Timestamp of latest update in Indian Standard Time (Asia/Kolkata).';
