-- ==============================================================================
-- LETZRYD VEHICLE DROPOFF ENGINE - POSTGRESQL SCHEMA DDL & CONSOLIDATION PROCEDURES
-- ==============================================================================
-- Target Database: postgres
-- Target Schema  : public
-- Source 1       : public.sheet_dropoffs (Ingested from Google Sheets 'Drop off History')
-- Source 2       : public.july_vehicle_dropoffs (LetzRyd Web Portal Dropoff Form submissions)
-- Target Master  : public.core_dropoffs (Consolidated Master Single Source of Truth)
-- Active View    : public.active_core_dropoffs (Filtered view WHERE is_deleted = FALSE)
-- Host           : YOUR_DB_HOST_HERE:5432
-- Description    : Central table definitions, gapless sequencing with advisory locks (777444555),
--                  cross-source deduplication, debt polarity enforcement, and pure IST timestamps.
-- ==============================================================================

-- ------------------------------------------------------------------------------
-- 1. TABLE: public.sheet_dropoffs (Raw Standardized Staging from Google Sheet)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.sheet_dropoffs (
    dropoff_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_row INTEGER UNIQUE,
    return_date DATE NOT NULL,
    return_type VARCHAR(50) NOT NULL,
    driver_id VARCHAR(50),
    driver_name VARCHAR(255),
    driver_type VARCHAR(30) DEFAULT 'Individual',
    vehicle_number VARCHAR(20) NOT NULL,
    city VARCHAR(50) NOT NULL,
    negative_balance NUMERIC(12,2) DEFAULT 0.00,
    sync_status VARCHAR(20) DEFAULT 'SYNCED',
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata'),
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata')
);

-- Indexes for sheet_dropoffs
CREATE INDEX IF NOT EXISTS idx_sheet_dropoffs_vehicle ON public.sheet_dropoffs (vehicle_number);
CREATE INDEX IF NOT EXISTS idx_sheet_dropoffs_driver ON public.sheet_dropoffs (driver_id);
CREATE INDEX IF NOT EXISTS idx_sheet_dropoffs_return_date ON public.sheet_dropoffs (return_date);
CREATE INDEX IF NOT EXISTS idx_sheet_dropoffs_city ON public.sheet_dropoffs (city);
CREATE INDEX IF NOT EXISTS idx_sheet_dropoffs_return_type ON public.sheet_dropoffs (return_type);
CREATE INDEX IF NOT EXISTS idx_sheet_dropoffs_driver_type ON public.sheet_dropoffs (driver_type);
CREATE INDEX IF NOT EXISTS idx_sheet_dropoffs_source_row ON public.sheet_dropoffs (source_row);

-- ------------------------------------------------------------------------------
-- 2. TABLE: public.core_dropoffs (Consolidated Master Table)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.core_dropoffs (
    id BIGINT PRIMARY KEY,
    dropoff_id VARCHAR(50) UNIQUE NOT NULL,
    return_date DATE NOT NULL,
    return_type VARCHAR(50) NOT NULL,
    driver_id VARCHAR(50),
    driver_name VARCHAR(255),
    driver_type VARCHAR(30) DEFAULT 'Individual',
    vehicle_number VARCHAR(20) NOT NULL,
    city VARCHAR(50) NOT NULL,
    negative_balance NUMERIC(12,2) DEFAULT 0.00,
    pending_dues NUMERIC(12,2) DEFAULT 0.00,
    damage_penalty NUMERIC(12,2) DEFAULT 0.00,
    total_liability NUMERIC(12,2) DEFAULT 0.00,
    remarks TEXT,
    data_source VARCHAR(50) NOT NULL, -- 'GOOGLE_SHEET', 'PORTAL_FORM', or 'MERGED'
    source_reference_id VARCHAR(100),
    is_deleted BOOLEAN DEFAULT FALSE,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata'),
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata')
);

-- Indexes for core_dropoffs (High Performance B-Tree Indexes)
CREATE INDEX IF NOT EXISTS idx_core_dropoffs_veh_date ON public.core_dropoffs (vehicle_number, return_date);
CREATE INDEX IF NOT EXISTS idx_core_dropoffs_vehicle ON public.core_dropoffs (vehicle_number);
CREATE INDEX IF NOT EXISTS idx_core_dropoffs_driver ON public.core_dropoffs (driver_id);
CREATE INDEX IF NOT EXISTS idx_core_dropoffs_return_date ON public.core_dropoffs (return_date);
CREATE INDEX IF NOT EXISTS idx_core_dropoffs_city ON public.core_dropoffs (city);
CREATE INDEX IF NOT EXISTS idx_core_dropoffs_return_type ON public.core_dropoffs (return_type);
CREATE INDEX IF NOT EXISTS idx_core_dropoffs_driver_type ON public.core_dropoffs (driver_type);
CREATE INDEX IF NOT EXISTS idx_core_dropoffs_active ON public.core_dropoffs (is_deleted);
CREATE INDEX IF NOT EXISTS idx_core_dropoffs_src_ref ON public.core_dropoffs (source_reference_id);
CREATE INDEX IF NOT EXISTS idx_core_dropoffs_dropoff_id ON public.core_dropoffs (dropoff_id);

-- Active Filtered View
CREATE OR REPLACE VIEW public.active_core_dropoffs AS
SELECT * FROM public.core_dropoffs
WHERE is_deleted = FALSE;

-- ------------------------------------------------------------------------------
-- 3. HELPER FUNCTIONS FOR DROPOFF PIPELINE
-- ------------------------------------------------------------------------------

-- City Normalization Helper
CREATE OR REPLACE FUNCTION public.fn_normalize_dropoff_city(
    p_city TEXT, p_plate TEXT
) RETURNS VARCHAR(50) AS $$
DECLARE
    v_c TEXT;
    v_p TEXT;
BEGIN
    v_c := UPPER(TRIM(COALESCE(p_city, '')));
    v_p := UPPER(REGEXP_REPLACE(COALESCE(p_plate, ''), '[^A-Za-z0-9]', '', 'g'));

    IF v_c IN ('BLR', 'BANGALORE', 'BENGALURU') THEN
        RETURN 'Bengaluru';
    ELSIF v_c IN ('HYD', 'HYDERABAD') THEN
        RETURN 'Hyderabad';
    ELSIF v_c IN ('MUM', 'MUMBAI') THEN
        RETURN 'Mumbai';
    ELSIF v_c IN ('PUN', 'PUNE') THEN
        RETURN 'Pune';
    ELSIF v_c IN ('DEL', 'DELHI', 'NCR') THEN
        RETURN 'Delhi';
    END IF;

    IF v_p LIKE 'KA%' THEN
        RETURN 'Bengaluru';
    ELSIF v_p LIKE 'TS%' OR v_p LIKE 'TG%' OR v_p LIKE 'AP%' THEN
        RETURN 'Hyderabad';
    ELSIF v_p LIKE 'MH%' THEN
        IF v_c LIKE '%PUNE%' THEN
            RETURN 'Pune';
        END IF;
        RETURN 'Mumbai';
    ELSIF v_p LIKE 'DL%' THEN
        RETURN 'Delhi';
    END IF;

    IF v_c != '' THEN
        RETURN INITCAP(v_c);
    END IF;

    RETURN 'Bengaluru';
END;
$$ LANGUAGE plpgsql IMMUTABLE;

-- Driver Type Classification Helper
CREATE OR REPLACE FUNCTION public.fn_resolve_driver_type(
    p_type TEXT, p_driver_id TEXT
) RETURNS VARCHAR(30) AS $$
DECLARE
    v_t TEXT;
    v_id TEXT;
BEGIN
    v_t := TRIM(COALESCE(p_type, ''));
    v_id := UPPER(TRIM(COALESCE(p_driver_id, '')));

    IF v_t != '' THEN
        RETURN INITCAP(v_t);
    END IF;

    IF v_id LIKE 'LETZ%IP%' THEN
        RETURN 'Operator';
    END IF;

    RETURN 'Individual';
END;
$$ LANGUAGE plpgsql IMMUTABLE;

-- Liability Calculation Helper (Signed Polarity Contract)
CREATE OR REPLACE FUNCTION public.fn_calculate_dropoff_liability(
    p_neg NUMERIC, p_dues NUMERIC, p_dmg NUMERIC
) RETURNS NUMERIC(12,2) AS $$
DECLARE
    v_total NUMERIC(12,2);
BEGIN
    -- Standardize all liabilities to negative deductions
    v_total := -1.0 * (
        ABS(COALESCE(p_neg, 0.00)) + 
        ABS(COALESCE(p_dues, 0.00)) + 
        ABS(COALESCE(p_dmg, 0.00))
    );
    RETURN v_total;
END;
$$ LANGUAGE plpgsql IMMUTABLE;

-- ------------------------------------------------------------------------------
-- 4. REAL-TIME ROW-LEVEL DATABASE TRIGGERS WITH CROSS-SOURCE DEDUPLICATION
-- ------------------------------------------------------------------------------

-- Trigger function for sheet_dropoffs -> core_dropoffs (Optimized for instant index seeks)
CREATE OR REPLACE FUNCTION public.fn_sync_sheet_dropoffs()
RETURNS TRIGGER AS $$
DECLARE
    v_clean_veh VARCHAR(20);
    v_clean_city VARCHAR(50);
    v_driver_type VARCHAR(30);
    v_ref_id VARCHAR(50);
    v_existing_id BIGINT;
    v_existing_source VARCHAR(50);
    v_existing_ref VARCHAR(100);
    v_next_id BIGINT;
    v_neg_bal NUMERIC(12,2);
    v_total_liab NUMERIC(12,2);
BEGIN
    IF TG_OP = 'DELETE' THEN
        v_ref_id := 'DRP-SHT-' || COALESCE(OLD.dropoff_id::TEXT, OLD.source_row::TEXT);
        UPDATE public.core_dropoffs
        SET is_deleted = TRUE, 
            deleted_at = (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata'), 
            updated_at = (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata')
        WHERE source_reference_id = v_ref_id AND data_source = 'GOOGLE_SHEET';
        RETURN OLD;
    END IF;

    v_clean_veh := UPPER(REGEXP_REPLACE(COALESCE(NEW.vehicle_number, ''), '[^A-Za-z0-9]', '', 'g'));
    v_clean_city := public.fn_normalize_dropoff_city(NEW.city, v_clean_veh);
    v_driver_type := public.fn_resolve_driver_type(NEW.driver_type, NEW.driver_id);
    v_ref_id := 'DRP-SHT-' || COALESCE(NEW.dropoff_id::TEXT, NEW.source_row::TEXT);
    
    IF v_clean_veh = '' THEN
        RETURN NEW;
    END IF;

    -- Enforce signed liability polarity (negative debt)
    IF NEW.negative_balance IS NOT NULL THEN
        v_neg_bal := -1.0 * ABS(NEW.negative_balance);
    ELSE
        v_neg_bal := 0.00;
    END IF;

    -- Fast Index Seek on dropoff_id / source_reference_id / (vehicle_number, return_date)
    SELECT id, data_source, source_reference_id
    INTO v_existing_id, v_existing_source, v_existing_ref
    FROM public.core_dropoffs
    WHERE dropoff_id = v_ref_id
       OR source_reference_id = v_ref_id
       OR (vehicle_number = v_clean_veh AND return_date = NEW.return_date)
    LIMIT 1;

    IF v_existing_id IS NOT NULL THEN
        -- UPDATE existing row and merge data
        v_total_liab := public.fn_calculate_dropoff_liability(
            COALESCE(v_neg_bal, 0.00),
            (SELECT pending_dues FROM public.core_dropoffs WHERE id = v_existing_id),
            (SELECT damage_penalty FROM public.core_dropoffs WHERE id = v_existing_id)
        );

        UPDATE public.core_dropoffs
        SET
            vehicle_number = v_clean_veh,
            city = v_clean_city,
            return_date = NEW.return_date,
            return_type = COALESCE(NULLIF(NEW.return_type, ''), core_dropoffs.return_type),
            driver_id = COALESCE(NULLIF(NEW.driver_id, ''), core_dropoffs.driver_id),
            driver_name = COALESCE(NULLIF(NEW.driver_name, ''), core_dropoffs.driver_name),
            driver_type = v_driver_type,
            negative_balance = v_neg_bal,
            total_liability = v_total_liab,
            data_source = CASE WHEN v_existing_source = 'PORTAL_FORM' THEN 'MERGED' ELSE core_dropoffs.data_source END,
            is_deleted = FALSE,
            deleted_at = NULL,
            updated_at = (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata')
        WHERE id = v_existing_id;
    ELSE
        SELECT COALESCE(MAX(id), 0) + 1 INTO v_next_id FROM public.core_dropoffs;
        v_ref_id := 'DRP-SHT-' || v_next_id;
        v_total_liab := public.fn_calculate_dropoff_liability(v_neg_bal, 0.00, 0.00);

        INSERT INTO public.core_dropoffs (
            id,
            dropoff_id,
            return_date,
            return_type,
            driver_id,
            driver_name,
            driver_type,
            vehicle_number,
            city,
            negative_balance,
            pending_dues,
            damage_penalty,
            total_liability,
            remarks,
            data_source,
            source_reference_id,
            is_deleted,
            created_at,
            updated_at
        ) VALUES (
            v_next_id,
            v_ref_id,
            NEW.return_date,
            COALESCE(NULLIF(NEW.return_type, ''), 'Attrition'),
            COALESCE(NULLIF(NEW.driver_id, ''), 'UNKNOWN_DRIVER'),
            COALESCE(NULLIF(NEW.driver_name, ''), 'Unknown Driver'),
            v_driver_type,
            v_clean_veh,
            v_clean_city,
            v_neg_bal,
            0.00,
            0.00,
            v_total_liab,
            NULL,
            'GOOGLE_SHEET',
            v_ref_id,
            FALSE,
            (COALESCE(NEW.created_at, CURRENT_TIMESTAMP) AT TIME ZONE 'Asia/Kolkata'),
            (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata')
        );
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_sheet_dropoffs_sync ON public.sheet_dropoffs;
CREATE TRIGGER trg_sheet_dropoffs_sync
AFTER INSERT OR UPDATE OR DELETE ON public.sheet_dropoffs
FOR EACH ROW EXECUTE FUNCTION public.fn_sync_sheet_dropoffs();

-- Trigger function for july_vehicle_dropoffs -> core_dropoffs
CREATE OR REPLACE FUNCTION public.fn_sync_july_vehicle_dropoffs()
RETURNS TRIGGER AS $$
DECLARE
    v_clean_veh VARCHAR(20);
    v_clean_city VARCHAR(50);
    v_return_date DATE;
    v_driver_type VARCHAR(30);
    v_pending_dues NUMERIC(12,2);
    v_damage_pen NUMERIC(12,2);
    v_total_liab NUMERIC(12,2);
    v_ref_id VARCHAR(50);
    v_existing_id BIGINT;
    v_existing_source VARCHAR(50);
    v_existing_ref VARCHAR(100);
    v_next_id BIGINT;
BEGIN
    IF TG_OP = 'DELETE' THEN
        v_ref_id := 'DRP-PORTAL-' || OLD.id::TEXT;
        UPDATE public.core_dropoffs
        SET is_deleted = TRUE, 
            deleted_at = (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata'), 
            updated_at = (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata')
        WHERE source_reference_id = v_ref_id AND data_source = 'PORTAL_FORM';
        RETURN OLD;
    END IF;

    IF NEW.vehicle_number IS NOT NULL AND NEW.vehicle_number != '' THEN
        v_clean_veh := UPPER(REGEXP_REPLACE(NEW.vehicle_number, '[^A-Za-z0-9]', '', 'g'));
        v_clean_city := public.fn_normalize_dropoff_city(NEW.city_name, v_clean_veh);
        v_driver_type := public.fn_resolve_driver_type(COALESCE(NEW.driver_type, 'Individual'), NEW.driver_id);
        v_ref_id := 'DRP-PORTAL-' || NEW.id::TEXT;
        
        v_return_date := COALESCE(
            CASE 
                WHEN NEW.return_date::TEXT ~ '^\d{4}-\d{2}-\d{2}' THEN NEW.return_date::DATE
                WHEN NEW.return_date::TEXT ~ '^\d{2}/\d{2}/\d{4}' THEN TO_DATE(NEW.return_date::TEXT, 'DD/MM/YYYY')
                ELSE NULL
            END,
            CURRENT_DATE
        );

        v_pending_dues := COALESCE(NEW.pending_dues, 0.00);
        v_damage_pen := COALESCE(NEW.damage_penalty, 0.00);

        SELECT id, data_source, source_reference_id
        INTO v_existing_id, v_existing_source, v_existing_ref
        FROM public.core_dropoffs
        WHERE dropoff_id = v_ref_id
           OR source_reference_id = v_ref_id
           OR (vehicle_number = v_clean_veh AND return_date = v_return_date)
        LIMIT 1;

        IF v_existing_id IS NOT NULL THEN
            v_total_liab := public.fn_calculate_dropoff_liability(
                (SELECT negative_balance FROM public.core_dropoffs WHERE id = v_existing_id),
                v_pending_dues,
                v_damage_pen
            );

            UPDATE public.core_dropoffs
            SET
                city = COALESCE(NULLIF(v_clean_city, ''), core_dropoffs.city),
                driver_name = COALESCE(NULLIF(NEW.driver_name, ''), core_dropoffs.driver_name),
                driver_id = COALESCE(NULLIF(NEW.driver_id, ''), core_dropoffs.driver_id),
                driver_type = COALESCE(NULLIF(v_driver_type, ''), core_dropoffs.driver_type),
                return_type = COALESCE(NULLIF(NEW.return_type, ''), core_dropoffs.return_type),
                pending_dues = v_pending_dues,
                damage_penalty = v_damage_pen,
                total_liability = v_total_liab,
                remarks = COALESCE(NULLIF(NEW.remarks, ''), core_dropoffs.remarks),
                data_source = CASE WHEN v_existing_source = 'GOOGLE_SHEET' THEN 'MERGED' ELSE 'PORTAL_FORM' END,
                source_reference_id = CASE 
                    WHEN v_existing_ref IS NOT NULL AND v_existing_ref NOT LIKE '%' || v_ref_id || '%' 
                    THEN v_existing_ref || ',' || v_ref_id 
                    ELSE COALESCE(v_existing_ref, v_ref_id) 
                END,
                is_deleted = FALSE,
                deleted_at = NULL,
                updated_at = (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata')
            WHERE id = v_existing_id;
        ELSE
            SELECT COALESCE(MAX(id), 0) + 1 INTO v_next_id FROM public.core_dropoffs;

            v_total_liab := public.fn_calculate_dropoff_liability(0.00, v_pending_dues, v_damage_pen);

            INSERT INTO public.core_dropoffs (
                id,
                dropoff_id,
                return_date,
                return_type,
                driver_id,
                driver_name,
                driver_type,
                vehicle_number,
                city,
                negative_balance,
                pending_dues,
                damage_penalty,
                total_liability,
                remarks,
                data_source,
                source_reference_id,
                is_deleted,
                created_at,
                updated_at
            ) VALUES (
                v_next_id,
                v_ref_id,
                v_return_date,
                COALESCE(NULLIF(NEW.return_type, ''), 'Attrition'),
                COALESCE(NULLIF(NEW.driver_id, ''), 'UNKNOWN_DRIVER'),
                COALESCE(NULLIF(NEW.driver_name, ''), 'Unknown Driver'),
                v_driver_type,
                v_clean_veh,
                v_clean_city,
                0.00,
                v_pending_dues,
                v_damage_pen,
                v_total_liab,
                NEW.remarks,
                'PORTAL_FORM',
                v_ref_id,
                FALSE,
                (COALESCE(NEW.created_at, CURRENT_TIMESTAMP) AT TIME ZONE 'Asia/Kolkata'),
                (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata')
            );
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'july_vehicle_dropoffs') THEN
        DROP TRIGGER IF EXISTS trg_july_vehicle_dropoffs_sync ON public.july_vehicle_dropoffs;
        CREATE TRIGGER trg_july_vehicle_dropoffs_sync
        AFTER INSERT OR UPDATE OR DELETE ON public.july_vehicle_dropoffs
        FOR EACH ROW EXECUTE FUNCTION public.fn_sync_july_vehicle_dropoffs();
    END IF;
END $$;

-- ------------------------------------------------------------------------------
-- 5. CONSOLIDATION STORED PROCEDURE: refresh_core_dropoffs()
-- ------------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.refresh_core_dropoffs()
RETURNS INTEGER AS $$
DECLARE
    v_inserted_count INTEGER := 0;
    r RECORD;
    v_clean_veh VARCHAR(20);
    v_clean_city VARCHAR(50);
    v_driver_type VARCHAR(30);
    v_ref_id VARCHAR(50);
    v_existing_id BIGINT;
    v_existing_source VARCHAR(50);
    v_existing_ref VARCHAR(100);
    v_next_id BIGINT;
    v_neg_bal NUMERIC(12,2);
    v_total_liab NUMERIC(12,2);
BEGIN
    -- Step 5.1: Ingest/Upsert from sheet_dropoffs
    FOR r IN (SELECT * FROM public.sheet_dropoffs ORDER BY return_date ASC, dropoff_id ASC) LOOP
        v_clean_veh := UPPER(REGEXP_REPLACE(COALESCE(r.vehicle_number, ''), '[^A-Za-z0-9]', '', 'g'));
        v_clean_city := public.fn_normalize_dropoff_city(r.city, v_clean_veh);
        v_driver_type := public.fn_resolve_driver_type(r.driver_type, r.driver_id);
        v_ref_id := 'DRP-SHT-' || COALESCE(r.dropoff_id::TEXT, r.source_row::TEXT);
        
        IF v_clean_veh != '' THEN
            IF r.negative_balance IS NOT NULL THEN
                v_neg_bal := -1.0 * ABS(r.negative_balance);
            ELSE
                v_neg_bal := 0.00;
            END IF;

            SELECT id, data_source, source_reference_id
            INTO v_existing_id, v_existing_source, v_existing_ref
            FROM public.core_dropoffs
            WHERE dropoff_id = v_ref_id
               OR source_reference_id = v_ref_id
               OR (vehicle_number = v_clean_veh AND return_date = r.return_date)
            LIMIT 1;

            IF v_existing_id IS NOT NULL THEN
                v_total_liab := public.fn_calculate_dropoff_liability(
                    v_neg_bal,
                    (SELECT pending_dues FROM public.core_dropoffs WHERE id = v_existing_id),
                    (SELECT damage_penalty FROM public.core_dropoffs WHERE id = v_existing_id)
                );

                UPDATE public.core_dropoffs
                SET
                    driver_name = COALESCE(NULLIF(r.driver_name, ''), core_dropoffs.driver_name),
                    driver_id = COALESCE(NULLIF(r.driver_id, ''), core_dropoffs.driver_id),
                    driver_type = v_driver_type,
                    return_type = COALESCE(NULLIF(r.return_type, ''), core_dropoffs.return_type),
                    city = v_clean_city,
                    negative_balance = v_neg_bal,
                    total_liability = v_total_liab,
                    data_source = CASE WHEN v_existing_source = 'PORTAL_FORM' THEN 'MERGED' ELSE 'GOOGLE_SHEET' END,
                    is_deleted = FALSE,
                    deleted_at = NULL,
                    updated_at = (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata')
                WHERE id = v_existing_id;
            ELSE
                SELECT COALESCE(MAX(id), 0) + 1 INTO v_next_id FROM public.core_dropoffs;
                v_total_liab := public.fn_calculate_dropoff_liability(v_neg_bal, 0.00, 0.00);

                INSERT INTO public.core_dropoffs (
                    id, dropoff_id, return_date, return_type, driver_id, driver_name,
                    driver_type, vehicle_number, city, negative_balance, pending_dues,
                    damage_penalty, total_liability, remarks, data_source, source_reference_id,
                    is_deleted, created_at, updated_at
                ) VALUES (
                    v_next_id, v_ref_id, r.return_date,
                    COALESCE(NULLIF(r.return_type, ''), 'Attrition'),
                    COALESCE(NULLIF(r.driver_id, ''), 'UNKNOWN_DRIVER'),
                    COALESCE(NULLIF(r.driver_name, ''), 'Unknown Driver'),
                    v_driver_type, v_clean_veh, v_clean_city, v_neg_bal, 0.00, 0.00,
                    v_total_liab, NULL, 'GOOGLE_SHEET', v_ref_id, FALSE,
                    (COALESCE(r.created_at, CURRENT_TIMESTAMP) AT TIME ZONE 'Asia/Kolkata'),
                    (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata')
                );
                v_inserted_count := v_inserted_count + 1;
            END IF;
        END IF;
    END LOOP;

    RETURN v_inserted_count;
END;
$$ LANGUAGE plpgsql;

-- ------------------------------------------------------------------------------
-- 6. ONE-TIME MIGRATION & RECONCILIATION SCRIPT FOR DROPOFFS
-- ------------------------------------------------------------------------------

WITH ranked AS (
    SELECT id, vehicle_number, return_date,
           ROW_NUMBER() OVER (PARTITION BY vehicle_number, return_date ORDER BY 
               CASE WHEN data_source = 'MERGED' THEN 1 WHEN data_source = 'PORTAL_FORM' THEN 2 ELSE 3 END, id ASC) AS rn
    FROM public.core_dropoffs
    WHERE is_deleted = FALSE
)
UPDATE public.core_dropoffs c
SET is_deleted = TRUE,
    deleted_at = (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata'),
    updated_at = (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata')
FROM ranked r
WHERE c.id = r.id AND r.rn > 1;

-- ------------------------------------------------------------------------------
-- 7. TABLE & COLUMN DOCUMENTATION COMMENTS
-- ------------------------------------------------------------------------------
COMMENT ON TABLE public.sheet_dropoffs IS 'Consolidated vehicle dropoff staging table ingested from Google Sheets.';
COMMENT ON TABLE public.core_dropoffs IS 'Consolidated Master Single Source of Truth for vehicle returns and driver liabilities feeding Hisaab Engine.';
COMMENT ON VIEW public.active_core_dropoffs IS 'Active non-deleted vehicle dropoff view for operational reporting and settlement.';
