-- ==============================================================================
-- LETZRYD - VEHICLE DROPOFF PIPELINE DDL (sheet_dropoffs)
-- ==============================================================================
-- Schema      : public
-- Table Name  : sheet_dropoffs
-- Primary Key : dropoff_id (BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)
-- Unique Key  : source_row (Exact row-to-record alignment)
-- Downstream  : Feeds dropoff_final (Driver Hisaab Engine)
-- ==============================================================================

-- 1. Create public.sheet_dropoffs table if not exists
CREATE TABLE IF NOT EXISTS public.sheet_dropoffs (
    -- Primary & Deterministic Alignment Keys
    dropoff_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_row INTEGER UNIQUE,
    
    -- Dropoff Core Attributes
    return_date DATE NOT NULL,
    return_type VARCHAR(50) NOT NULL,
    
    -- Driver & Operator Details
    driver_id VARCHAR(50),
    driver_name VARCHAR(100),
    driver_type VARCHAR(30) DEFAULT 'Individual',
    
    -- Vehicle & Location
    vehicle_number VARCHAR(20) NOT NULL,
    city VARCHAR(50) NOT NULL,
    
    -- Financial Liability (Supports Negative Liabilities & NULL for Pending/TBD)
    negative_balance NUMERIC(12, 2) DEFAULT 0.00,
    
    -- Soft-Delete & Audit Timestamps
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,
    sync_status VARCHAR(20) DEFAULT 'SYNCED',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 2. High-Performance B-Tree Indexes
CREATE INDEX IF NOT EXISTS idx_sheet_dropoffs_vehicle ON public.sheet_dropoffs(vehicle_number);
CREATE INDEX IF NOT EXISTS idx_sheet_dropoffs_driver ON public.sheet_dropoffs(driver_id);
CREATE INDEX IF NOT EXISTS idx_sheet_dropoffs_return_date ON public.sheet_dropoffs(return_date);
CREATE INDEX IF NOT EXISTS idx_sheet_dropoffs_city ON public.sheet_dropoffs(city);
CREATE INDEX IF NOT EXISTS idx_sheet_dropoffs_return_type ON public.sheet_dropoffs(return_type);
CREATE INDEX IF NOT EXISTS idx_sheet_dropoffs_driver_type ON public.sheet_dropoffs(driver_type);
CREATE INDEX IF NOT EXISTS idx_sheet_dropoffs_source_row ON public.sheet_dropoffs(source_row);

-- 3. Row-Level Normalization Trigger for Portal Dropoffs (july_vehicle_dropoffs)
CREATE OR REPLACE FUNCTION public.fn_sync_dropoff_from_portal()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;

    -- Automatically normalize city and vehicle plate
    NEW.city_name := CASE 
        WHEN LOWER(TRIM(COALESCE(NEW.city_name, ''))) IN ('bangalore', 'bengaluru', 'blr') THEN 'Bangalore'
        WHEN LOWER(TRIM(COALESCE(NEW.city_name, ''))) IN ('hyderabad', 'hyd') THEN 'Hyderabad'
        WHEN LOWER(TRIM(COALESCE(NEW.city_name, ''))) IN ('mumbai', 'mum') THEN 'Mumbai'
        ELSE LEFT(INITCAP(TRIM(COALESCE(NEW.city_name, 'Bangalore'))), 50)
    END;

    NEW.vehicle_number := UPPER(REGEXP_REPLACE(COALESCE(NEW.vehicle_number, ''), '[^A-Za-z0-9]', '', 'g'));
    NEW.pending_dues := COALESCE(NEW.pending_dues, 0.00);
    NEW.damage_penalty := COALESCE(NEW.damage_penalty, 0.00);

    RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS trg_sync_dropoff_from_portal ON public.july_vehicle_dropoffs;
CREATE TRIGGER trg_sync_dropoff_from_portal
BEFORE INSERT OR UPDATE ON public.july_vehicle_dropoffs
FOR EACH ROW EXECUTE FUNCTION public.fn_sync_dropoff_from_portal();

-- 4. Table & Column Documentation Comments
COMMENT ON TABLE public.sheet_dropoffs IS 'Consolidated vehicle dropoff and return logs feeding downstream dropoff_final in Hisaab Engine.';
COMMENT ON COLUMN public.sheet_dropoffs.dropoff_id IS 'Auto-incrementing primary key backed by sequence.';
COMMENT ON COLUMN public.sheet_dropoffs.source_row IS 'Exact 1:1 spreadsheet row index ensuring zero-desync live synchronization.';
COMMENT ON COLUMN public.sheet_dropoffs.return_date IS 'Standardized ISO return date (YYYY-MM-DD).';
COMMENT ON COLUMN public.sheet_dropoffs.return_type IS 'Reason for vehicle return (Attrition, Repair and Maintenance, Force Recovery).';
COMMENT ON COLUMN public.sheet_dropoffs.negative_balance IS 'Ola negative wallet balance / outstanding driver liability (NUMERIC 12,2).';
COMMENT ON COLUMN public.sheet_dropoffs.city IS 'Canonical city name (Bangalore, Hyderabad, Mumbai).';
